Characters = {'tommahs': {
                        'name' : 'Tommahs',
                        'class' : 'Warrior',
                        'lvl' : 1,
                        'xp' : 0,
                        'xptonextlvl' : 25,
                        'rewardXp': 0,
                        'skillpoints': 0,
                        'stats': {'str': 1,
                                  'dex' : 10,
                                  'con' : 1,
                                  'int' : 1,
                                  'wis' : 1,
                                  'cha' : 1,
                                  'hp' : 20,
                                  'maxhp': 20,
                                  'atk' : [5,12]},
                        'record' : {},
                        },
            'tess': {
                        'name' : 'Tess',
                        'class' : 'Mage',
                        'lvl' : 1,
                        'xp' : 0,
                        'xptonextlvl' : 25,
                        'rewardXp' : 0,
                        'skillpoints': 0,
                        'stats': {'str': 1,
                                  'dex' : 10,
                                  'con' : 1,
                                  'int' : 1,
                                  'wis' : 1,
                                  'cha' : 1,
                                  'hp' : 20,
                                  'maxhp': 20,
                                  'atk' : [5,12]},
                        'record': {}
                        }
            }